AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Style/FrozenStringLiteralComment:
  Enabled: true

# Specs often have multiline block chains
Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'

# Disable predicate method naming rule
Naming/PredicateMethod:
  Enabled: false

# Allow development dependencies in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Enforce first argument on new line for multiline method calls
Layout/FirstMethodArgumentLineBreak:
  Enabled: true

# Use fixed indentation for arguments
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Ensure closing parenthesis on new line for multiline calls
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
